export const verseCount = [
  7, 286, 200, 176, 120, 165, 206, 75, 129, 109, 123, 111, 43, 52, 99, 128, 111,
  110, 98, 135, 112, 78, 118, 64, 77, 227, 93, 88, 69, 60, 34, 30, 73, 54, 45,
  83, 182, 88, 75, 85, 54, 53, 89, 59, 37, 35, 38, 29, 18, 45, 60, 49, 62, 55,
  78, 96, 29, 22, 24, 13, 14, 11, 11, 18, 12, 12, 30, 52, 52, 44, 28, 28, 20,
  56, 40, 31, 50, 40, 46, 42, 29, 19, 36, 25, 22, 17, 19, 26, 30, 20, 15, 21,
  11, 8, 8, 19, 5, 8, 8, 11, 11, 8, 3, 9, 5, 4, 7, 3, 6, 3, 5, 4, 5, 6,
];

export const quranChapter: { [key: string]: string } = {
  "Al-Fatihah": "The Opening",
  "Al-Baqarah": "The Cow",
  "Al-Imran": "The Family of Imran",
  "An-Nisa": "The Women",
  "Al-Ma'idah": "The Table",
  "Al-An'am": "The Cattle",
  "Al-A'raf": "The Elevated Places",
  "Al-Anfal": "The Spoils of War",
  "At-Tawbah": "The Repentance",
  Yunus: "Jonah",
  Hud: "Hud",
  Yusuf: "Joseph",
  "Ar-Ra'd": "The Thunder",
  Ibrahim: "Abraham",
  "Al-Hijr": "The Rock",
  "An-Nahl": "The Bee",
  "Al-Isra": "The Night Journey",
  "Al-Kahf": "The Cave",
  Maryam: "Mary",
  Taha: "Taha",
  "Al-Anbiya": "The Prophets",
  "Al-Hajj": "The Pilgrimage",
  "Al-Muminun": "The Believers",
  "An-Nur": "The Light",
  "Al-Furqan": "The Criterion",
  "Ash-Shu'ara": "The Poets",
  "An-Naml": "The Ant",
  "Al-Qasas": "The Narratives",
  "Al-Ankabut": "The Spider",
  "Ar-Rum": "The Romans",
  Luqman: "Luqman",
  "As-Sajdah": "The Prostration",
  "Al-Ahzab": "The Combined Forces",
  Saba: "Sheba",
  Fatir: "The Originator",
  "Ya-Sin": "Ya-Sin",
  "As-Saffat": "Those Who Set the Ranks",
  Sad: "The Letter 'Sad'",
  "Az-Zumar": "The Groups",
  Ghafir: "The Forgiver",
  Fussilat: "Explained in Detail",
  "Ash-Shura": "The Consultation",
  "Az-Zukhruf": "The Ornaments of Gold",
  "Ad-Dukhan": "The Smoke",
  "Al-Jathiyah": "The Crouching",
  "Al-Ahqaf": "The Dunes",
  Muhammad: "Muhammad",
  "Al-Fath": "The Victory",
  "Al-Hujurat": "The Inner Apartments",
  Qaf: "The Letter 'Qaf'",
  "Adh-Dhariyat": "The Winnowing Winds",
  "At-Tur": "The Mount",
  "An-Najm": "The Star",
  "Al-Qamar": "The Moon",
  "Ar-Rahman": "The Most Gracious",
  "Al-Waqi'ah": "The Event",
  "Al-Hadid": "The Iron",
  "Al-Mujadilah": "The Pleading Woman",
  "Al-Hashr": "The Banishment",
  "Al-Mumtahanah": "The Examined One",
  "As-Saff": "The Ranks",
  "Al-Jumu'ah": "The Congregation",
  "Al-Munafiqun": "The Hypocrites",
  "At-Taghabun": "The Mutual Disillusion",
  "At-Talaq": "The Divorce",
  "At-Tahrim": "The Prohibition",
  "Al-Mulk": "The Sovereignty",
  "Al-Qalam": "The Pen",
  "Al-Haqqah": "The Reality",
  "Al-Ma'arij": "The Ascending Stairways",
  Nuh: "Noah",
  "Al-Jinn": "The Jinn",
  "Al-Muzzammil": "The Enshrouded One",
  "Al-Muddaththir": "The Cloaked One",
  "Al-Qiyamah": "The Resurrection",
  "Al-Insan": "The Man",
  "Al-Mursalat": "The Emissaries",
  "An-Naba": "The Announcement",
  "An-Nazi'at": "Those Who Drag Forth",
  "'Abasa": "He Frowned",
  "At-Takwir": "The Overthrowing",
  "Al-Infitar": "The Cleaving",
  "Al-Mutaffifin": "The Defrauding",
  "Al-Inshiqaq": "The Splitting Open",
  "Al-Buruj": "The Constellations",
  "At-Tariq": "The Morning Star",
  "Al-A'la": "The Most High",
  "Al-Ghashiyah": "The Overwhelming",
  "Al-Fajr": "The Dawn",
  "Al-Balad": "The City",
  "Ash-Shams": "The Sun",
  "Al-Lail": "The Night",
  "Ad-Duha": "The Forenoon",
  "Ash-Sharh": "The Relief",
  "At-Tin": "The Fig",
  "Al-'Alaq": "The Clot",
  "Al-Qadr": "The Power",
  "Al-Bayyinah": "The Clear Evidence",
  "Az-Zalzalah": "The Earthquake",
  "Al-'Adiyat": "The Chargers",
  "Al-Qari'ah": "The Calamity",
  "At-Takathur": "The Abundance of Wealth",
  "Al-Asr": "The Time",
  "Al-Humazah": "The Slanderer",
  "Al-Fil": "The Elephant",
  Quraysh: "The Qureysh",
  "Al-Ma'un": "Acts of Kindness",
  "Al-Kawthar": "The Abundance",
  "Al-Kafirun": "The Disbelievers",
  "An-Nasr": "The Help",
  "Al-Lahab": "The Flame",
  "Al-Ikhlas": "The Sincerity",
  "Al-Falaq": "The Daybreak",
  "An-Nas": "The People",
};
